name : CI

on :
  push :

jobs :
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'

      - name: Check Go version
        run: go version


      - name: Download dependencies
        run: go mod tidy


      - name: Build
        run: go build -v ./...


      - name: Run tests
        run: go test ./...